site_name: Polytope
theme:
    name: readthedocs
    icon:
        admonition:
            shapes: :material-shape
    logo: images/logo_read_the_docs.png
markdown_extensions:
    - admonition
    # - pymdownx.details
    # - pymdownx.superfences
extra_css:
    - extra.css
nav: 
    - Home: index.md
    - Overview: 
        - Overview: Overview/Overview.md
        - Polytope at ECMWF: Overview/Polytope_at_ECMWF.md
    - User Guide: 
        - Overview: User_Guide/Overview.md
        - Getting Started: User_Guide/Getting_started.md
        - Example: User_Guide/Example.md
    - Developer Guide:
        - Overview: Developer_Guide/Overview.md
        - Datacube: Developer_Guide/Datacube.md
        - Slicer: Developer_Guide/Slicer.md
        - APIs: Developer_Guide/API.md
            # - API levels: Developer_Guide/API.md
            # - Mid-level Shapes: Developer_Guide/shapes.md
